Traceback (most recent call last):
  File "/Users/psbang008/.opam/4.05.0/lib/lymp/lymp.py", line 90, in loop
    self.send_ret(ret, ret_ref=("R" in instruction))
  File "/Users/psbang008/.opam/4.05.0/lib/lymp/lymp.py", line 129, in send_ret
    self.reader_writer.send_bytes(msg)
  File "/Users/psbang008/.opam/4.05.0/lib/lymp/lymp.py", line 39, in send_bytes
    self.write_pipe.write(pack('>q', len(byts)))
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/Users/psbang008/.opam/4.05.0/lib/lymp/lymp.py", line 90, in loop
    self.send_ret(ret, ret_ref=("R" in instruction))
  File "/Users/psbang008/.opam/4.05.0/lib/lymp/lymp.py", line 129, in send_ret
    self.reader_writer.send_bytes(msg)
  File "/Users/psbang008/.opam/4.05.0/lib/lymp/lymp.py", line 39, in send_bytes
    self.write_pipe.write(pack('>q', len(byts)))
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/psbang008/.opam/4.05.0/lib/lymp/lymp.py", line 211, in <module>
    handler.loop()
  File "/Users/psbang008/.opam/4.05.0/lib/lymp/lymp.py", line 96, in loop
    self.send_ret("", exception=True)
  File "/Users/psbang008/.opam/4.05.0/lib/lymp/lymp.py", line 129, in send_ret
    self.reader_writer.send_bytes(msg)
  File "/Users/psbang008/.opam/4.05.0/lib/lymp/lymp.py", line 39, in send_bytes
    self.write_pipe.write(pack('>q', len(byts)))
BrokenPipeError: [Errno 32] Broken pipe
